---
branches:
  - main
  # TODO Remove before merge
  - chore/automate-versioning-and-releases
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - - "@semantic-release/git"
    - message: |-
        chore(release): ${nextRelease.version} [skip ci]

        ${nextRelease.notes}
