# .terraform-docs.yml
content: |-
  {{ .Header }}

  ## MVP Example

  ```hcl
  {{ include "examples/minimal/main.tf" }}
  ```

  ## Example using Private Services Connect (PSC)
  ```hcl
  {{ include "examples/psc/main.tf" }}
  ```

  {{ .Inputs }}

  {{ .Outputs }}  

