content: |-
  {{ .Header }}

  ## Examples

  ```hcl
  {{ include "examples/example.tf" }}
  {{ include "examples/example_maintenance_page.tf" }}
  {{ include "examples/example_stage.tf" }}
  ```

  {{ .Inputs }}

  {{ .Outputs }}
