name: Terraform CI

on:
- push
- pull_request

permissions: {}

jobs:
  matrixify:
    name: Matrixify
    outputs:
      matrix: ${{ steps.search.outputs.matrix }}
    runs-on: ubuntu-latest

    steps:
    - name: Get Changed Terraform directories
      id: search
      uses: mozilla/tf-actions/matrixify@main
      with:
        ignore_dir: "**/example**"
    - name: Outputs
      run: echo "${OUTPUTS_MATRIX}"
      env:
        OUTPUTS_MATRIX: ${{ steps.search.outputs.matrix }}

  terraform-ci:
    name: Terraform CI on "${{ matrix.directory }}"

    if: ${{ fromJSON(needs.matrixify.outputs.matrix).include[0] }}
    needs: matrixify
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.matrixify.outputs.matrix)}}

    steps:
    - name: Install terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - id: terraform-checks
      name: Terraform Checks
      uses: mozilla/tf-actions/ci@v0.0.4
      with:
        readme_check: "true"
        tfpath: ${{ matrix.directory }}
