name: 'Monorepo: Release'
on:
  repository_dispatch:
    types: [monorepo_release]

jobs:

  tag:
    runs-on: ubuntu-latest
    name: 'Tag Releases'
    steps:

      - uses: actions/github-script@v2
        env:
          CLIENT_PAYLOAD: ${{ toJSON(github.event.client_payload) }}
        with:
          script: |
            const { owner, repo } = context.repo;
            const { sha, releases } = JSON.parse(process.env.CLIENT_PAYLOAD);

            for (const release of releases) {
              const tagName = `rel/${release.module}/${release.newVersion}`;

              const ref = `refs/tags/${tagName}`;
              console.log('Tagging', tagName, 'as', sha);
              await github.git.createRef({ owner, repo, ref, sha });
            }
